name: Fabricar mi APK
on:
  push:
    branches: [ master, main ] # Se activa al guardar cambios
  workflow_dispatch: # Te permite darle al botón "Run" manualmente

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi_Primer_Juego
          path: bin/*.apk
